# Generated by Django 5.1.7 on 2025-10-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Activity Page',
                'verbose_name_plural': 'Activity Pages',
            },
        ),
        migrations.CreateModel(
            name='ActivitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('participants', models.PositiveIntegerField(blank=True, null=True)),
                ('date_range', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='App.activity')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_portrait', models.BooleanField(default=False, help_text='เช็คถ้าต้องการให้รูปสูง (70vh)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='App.activitysection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
