# Generated by Django 5.1.7 on 2025-10-26 15:41

import App.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'รูปภาพกิจกรรม', 'verbose_name_plural': 'รูปภาพกิจกรรม'},
        ),
        migrations.AlterModelOptions(
            name='activitysection',
            options={'ordering': ['order', 'id'], 'verbose_name': 'หัวข้อกิจกรรม', 'verbose_name_plural': 'หัวข้อกิจกรรม'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(help_text='เช่น Outing Activity', max_length=200, verbose_name='ชื่อหน้า'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, help_text="ใช้ใน URL เช่น 'outing' (ปล่อยว่างให้ระบบสร้างอัตโนมัติได้)", max_length=80, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='ข้อความใต้หัวเรื่อง'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='คำบรรยาย'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=models.ImageField(upload_to=App.models.activity_image_upload_to, verbose_name='ไฟล์รูป'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='is_portrait',
            field=models.BooleanField(default=False, help_text='ติ๊กถ้าต้องการให้รูปสูง (70vh)', verbose_name='รูปแนวตั้ง'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='เลขยิ่งน้อยยิ่งอยู่บน', verbose_name='ลำดับแสดง'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='App.activitysection', verbose_name='หัวข้อ'),
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='App.activity', verbose_name='อยู่ในหน้า'),
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='date_range',
            field=models.CharField(blank=True, help_text='เช่น 18–19 พ.ค. 2024', max_length=120, verbose_name='ช่วงวันที่'),
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='สถานที่'),
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='เลขยิ่งน้อยยิ่งอยู่บน', verbose_name='ลำดับแสดง'),
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ผู้เข้าร่วม (คน)'),
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='หัวข้อ'),
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='year',
            field=models.CharField(blank=True, help_text='ใส่ปี (เช่น 2024) หรือปล่อยว่าง', max_length=10, verbose_name='ปี (แสดงผล)'),
        ),
        migrations.AddConstraint(
            model_name='activityimage',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='uniq_image_order_per_section'),
        ),
        migrations.AddConstraint(
            model_name='activitysection',
            constraint=models.UniqueConstraint(fields=('activity', 'order'), name='uniq_section_order_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='activitysection',
            constraint=models.UniqueConstraint(fields=('activity', 'title'), name='uniq_section_title_per_activity'),
        ),
    ]
