# Generated by Django 5.1.7 on 2025-10-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_activityimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysection',
            name='date_range',
        ),
        migrations.AddField(
            model_name='activitysection',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุด'),
        ),
        migrations.AddField(
            model_name='activitysection',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เริ่ม'),
        ),
    ]
