# Generated by Django 5.1.7 on 2025-10-26 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_activitysection_date_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ชื่อกลุ่มเมนู')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='รหัสกลุ่ม (ไม่ซ้ำ)')),
            ],
            options={
                'verbose_name': 'เมนู (กลุ่ม)',
                'verbose_name_plural': 'เมนู (กลุ่ม)',
            },
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='year',
            field=models.CharField(blank=True, help_text='เช่น 2024 หรือปล่อยว่าง', max_length=10, verbose_name='ปี (แสดงผล)'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='ข้อความเมนู')),
                ('named_url', models.CharField(blank=True, help_text="เช่น 'contact_us' หรือ 'activity_detail' (จะ reverse ให้อัตโนมัติ)", max_length=200, verbose_name='Django named URL')),
                ('url', models.CharField(blank=True, help_text='เช่น /careers/job-openings/ หรือ https://example.com', max_length=500, verbose_name='External URL')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='เปิดแท็บใหม่')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('activity_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.activity', verbose_name='ลิงก์ไป Activity')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App.menu', verbose_name='อยู่ในเมนู')),
            ],
            options={
                'verbose_name': 'เมนู (รายการ)',
                'verbose_name_plural': 'เมนู (รายการ)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
